[2025-04-18T12:14:16.142+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T12:14:16.194+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_to_gcs.transform_csv scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2025-04-18T12:14:16.246+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_to_gcs.transform_csv scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2025-04-18T12:14:16.254+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-18T12:14:16.296+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): transform_csv> on 2004-01-01 00:00:00+00:00
[2025-04-18T12:14:16.328+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2826) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-18T12:14:16.331+0000] {standard_task_runner.py:72} INFO - Started process 2848 to run task
[2025-04-18T12:14:16.325+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_to_gcs', 'transform_csv', 'scheduled__2004-01-01T00:00:00+00:00', '--job-id', '577', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_to_gcs.py', '--cfg-path', '/tmp/tmp9ogw_u31']
[2025-04-18T12:14:16.335+0000] {standard_task_runner.py:105} INFO - Job 577: Subtask transform_csv
[2025-04-18T12:14:16.478+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_to_gcs.transform_csv scheduled__2004-01-01T00:00:00+00:00 [running]> on host f21ba0bbe878
[2025-04-18T12:14:16.764+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_to_gcs' AIRFLOW_CTX_TASK_ID='transform_csv' AIRFLOW_CTX_EXECUTION_DATE='2004-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2004-01-01T00:00:00+00:00'
[2025-04-18T12:14:16.766+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T12:14:35.076+0000] {job.py:229} INFO - Heartbeat recovered after 19.12 seconds
[2025-04-18T12:15:08.009+0000] {job.py:229} INFO - Heartbeat recovered after 11.91 seconds
[2025-04-18T12:15:08.196+0000] {local_task_job_runner.py:266} INFO - Task exited with return code -9. For more information, see https://***.apache.org/docs/apache-***/stable/troubleshooting.html#LocalTaskJob-killed
[2025-04-18T12:15:08.451+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T12:15:08.471+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-04-18T12:15:08.473+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
