[2025-04-13T21:17:53.340+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-13T21:17:58.228+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_dlt_data_pipeline.download_file scheduled__1989-01-01T00:00:00+00:00 [queued]>
[2025-04-13T21:17:58.349+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_dlt_data_pipeline.download_file scheduled__1989-01-01T00:00:00+00:00 [queued]>
[2025-04-13T21:17:58.384+0000] {taskinstance.py:2867} INFO - Starting attempt 7 of 8
[2025-04-13T21:17:58.559+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): download_file> on 1989-01-01 00:00:00+00:00
[2025-04-13T21:17:58.620+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=533) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-13T21:17:58.628+0000] {standard_task_runner.py:72} INFO - Started process 567 to run task
[2025-04-13T21:17:58.620+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'gcs_dlt_data_pipeline', 'download_file', 'scheduled__1989-01-01T00:00:00+00:00', '--job-id', '304', '--raw', '--subdir', 'DAGS_FOLDER/first_stage/first_stage.py', '--cfg-path', '/tmp/tmpwuzzrvt2']
[2025-04-13T21:17:58.635+0000] {standard_task_runner.py:105} INFO - Job 304: Subtask download_file
[2025-04-13T21:18:11.264+0000] {cli_action_loggers.py:177} WARNING - Failed to log action (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-13T21:18:13.055+0000] {job.py:229} INFO - Heartbeat recovered after 22.28 seconds
[2025-04-13T21:18:13.268+0000] {task_command.py:467} INFO - Running <TaskInstance: gcs_dlt_data_pipeline.download_file scheduled__1989-01-01T00:00:00+00:00 [running]> on host 3330be1269a6
[2025-04-13T21:18:13.937+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_dlt_data_pipeline' AIRFLOW_CTX_TASK_ID='download_file' AIRFLOW_CTX_EXECUTION_DATE='1989-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='scheduled__1989-01-01T00:00:00+00:00'
[2025-04-13T21:18:13.963+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-13T21:18:14.150+0000] {logging_mixin.py:190} INFO - Source File Path: raw/1989.csv.bz2
[2025-04-13T21:18:14.165+0000] {logging_mixin.py:190} INFO - Destination File Path: /tmp/1989.csv.bz2
[2025-04-13T21:18:14.173+0000] {logging_mixin.py:190} INFO - Downloading raw/1989.csv.bz2 from bucket db_project_data_bucket to /tmp/1989.csv.bz2
[2025-04-13T21:18:30.286+0000] {logging_mixin.py:190} INFO - Downloaded db_project_data_bucket/raw/1989.csv.bz2 to /tmp/1989.csv.bz2
[2025-04-13T21:19:01.804+0000] {local_task_job_runner.py:266} INFO - Task exited with return code -9. For more information, see https://***.apache.org/docs/apache-***/stable/troubleshooting.html#LocalTaskJob-killed
[2025-04-13T21:19:01.969+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-13T21:19:01.976+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
