[2025-04-13T21:17:53.340+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-13T21:17:58.229+0000] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: gcs_dlt_data_pipeline.download_file scheduled__1994-01-01T00:00:00+00:00 [queued]>, dependency 'Execution Date' FAILED: The execution date is 1994-01-01T00:00:00+00:00 but this is after the task's end date 1992-01-01T00:00:00+00:00.
[2025-04-13T21:17:58.242+0000] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: gcs_dlt_data_pipeline.download_file scheduled__1994-01-01T00:00:00+00:00 [queued]>, dependency 'Execution Date' FAILED: The execution date is 1994-01-01T00:00:00+00:00 but this is after the task's DAG's end date 1992-01-01T00:00:00+00:00.
[2025-04-13T21:17:58.269+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
