[2025-04-17T21:00:23.029+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-17T21:00:23.047+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_to_gcs.download_csv_from_kaggle scheduled__1988-01-01T00:00:00+00:00 [queued]>
[2025-04-17T21:00:23.056+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_to_gcs.download_csv_from_kaggle scheduled__1988-01-01T00:00:00+00:00 [queued]>
[2025-04-17T21:00:23.057+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 4
[2025-04-17T21:00:23.085+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): download_csv_from_kaggle> on 1988-01-01 00:00:00+00:00
[2025-04-17T21:00:23.101+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_to_gcs', 'download_csv_from_kaggle', 'scheduled__1988-01-01T00:00:00+00:00', '--job-id', '551', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_to_gcs.py', '--cfg-path', '/tmp/tmp46gy9wvd']
[2025-04-17T21:00:23.106+0000] {standard_task_runner.py:105} INFO - Job 551: Subtask download_csv_from_kaggle
[2025-04-17T21:00:23.111+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1938) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-17T21:00:23.113+0000] {standard_task_runner.py:72} INFO - Started process 1940 to run task
[2025-04-17T21:00:23.179+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_to_gcs.download_csv_from_kaggle scheduled__1988-01-01T00:00:00+00:00 [running]> on host f21ba0bbe878
[2025-04-17T21:00:23.295+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_to_gcs' AIRFLOW_CTX_TASK_ID='download_csv_from_kaggle' AIRFLOW_CTX_EXECUTION_DATE='1988-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__1988-01-01T00:00:00+00:00'
[2025-04-17T21:00:23.296+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-17T21:00:23.323+0000] {logging_mixin.py:190} INFO - Dataset URL: https://www.kaggle.com/datasets/viggo123/data-fight-usa-dataset
[2025-04-17T21:01:51.608+0000] {job.py:229} INFO - Heartbeat recovered after 28.66 seconds
[2025-04-17T21:01:51.629+0000] {local_task_job_runner.py:266} INFO - Task exited with return code -9. For more information, see https://***.apache.org/docs/apache-***/stable/troubleshooting.html#LocalTaskJob-killed
[2025-04-17T21:01:51.691+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-17T21:01:51.701+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
